WITH lagged AS
(SELECT "CURRENCY", "CURRENCY_DENOM", "TIME_PERIOD", "OBS_VALUE",
		LAG("OBS_VALUE") OVER(PARTITION BY "CURRENCY", "CURRENCY_DENOM" ORDER BY "TIME_PERIOD") AS last_val
FROM rates)
SELECT *
FROM lagged
ORDER BY ("OBS_VALUE" - last_val) / "OBS_VALUE"
FETCH FIRST 10 ROWS ONLY;